/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.fei.view;

import br.edu.fei.controller.BuscarAnimeController;
import br.edu.fei.model.Usuarios;

/**
 *
 * @author sabri
 */
public class JFrameBuscarAnime extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameBuscarAnime.class.getName());

    private Usuarios usuarioLogado;
    private BuscarAnimeController buscarAnimeController;

    public JFrameBuscarAnime(Usuarios usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        this.buscarAnimeController = new BuscarAnimeController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionarFavorito = new javax.swing.JButton();
        btnAdicionarFavorito1 = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        pesquisar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimes = new javax.swing.JTable();
        btnCurtir = new javax.swing.JButton();
        btnDescurtir = new javax.swing.JButton();
        FEIFLIX = new javax.swing.JLabel();
        btnAdicionarFavorito2 = new javax.swing.JButton();

        btnAdicionarFavorito.setText("Adicionar anime");

        btnAdicionarFavorito1.setText("Adicionar anime");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pesquisar.setText("Pesquisar:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        tblAnimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Descrição", "Duração em minutos", "Gênero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnimes);

        btnCurtir.setText("Curtir");
        btnCurtir.addActionListener(this::btnCurtirActionPerformed);

        btnDescurtir.setText("descurtir");
        btnDescurtir.addActionListener(this::btnDescurtirActionPerformed);

        FEIFLIX.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        FEIFLIX.setForeground(new java.awt.Color(204, 0, 0));
        FEIFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FEIFLIX.setText("FEIFLIX");
        FEIFLIX.setToolTipText("");
        FEIFLIX.setPreferredSize(new java.awt.Dimension(100, 16));

        btnAdicionarFavorito2.setText("Adicionar anime");
        btnAdicionarFavorito2.addActionListener(this::btnAdicionarFavorito2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCurtir)
                        .addGap(33, 33, 33)
                        .addComponent(btnDescurtir)
                        .addGap(34, 34, 34)
                        .addComponent(btnAdicionarFavorito2)
                        .addGap(139, 139, 139)
                        .addComponent(FEIFLIX, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnCurtir)
                            .addComponent(btnDescurtir)
                            .addComponent(btnAdicionarFavorito2))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FEIFLIX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarAnimeController.buscarAnime(txtBusca, tblAnimes, this);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        buscarAnimeController.voltarParaMenu(this, usuarioLogado);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        buscarAnimeController.curtirAnime(usuarioLogado, tblAnimes, this);
    }//GEN-LAST:event_btnCurtirActionPerformed

    private void btnDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescurtirActionPerformed
        buscarAnimeController.descurtirAnime(usuarioLogado, tblAnimes, this);
    }//GEN-LAST:event_btnDescurtirActionPerformed

    private void btnAdicionarFavorito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFavorito2ActionPerformed
        buscarAnimeController.adicionarAosFavoritos(usuarioLogado, tblAnimes, this);
    }//GEN-LAST:event_btnAdicionarFavorito2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new JFrameBuscarAnime().setVisible(true));
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FEIFLIX;
    private javax.swing.JButton btnAdicionarFavorito;
    private javax.swing.JButton btnAdicionarFavorito1;
    private javax.swing.JButton btnAdicionarFavorito2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnDescurtir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JTable tblAnimes;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}