/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.fei.view;

import br.edu.fei.model.Usuarios;
import br.edu.fei.model.Animes;
import br.edu.fei.model.dao.AnimesDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.edu.fei.model.dao.AvaliacoesDAO;

/**
 *
 * @author sabri
 */
public class JFrameBuscarAnime extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameBuscarAnime.class.getName());

    private Usuarios usuarioLogado;

    public JFrameBuscarAnime(Usuarios usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;

        configurarTabela();
    }

    private void configurarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Título");
        modelo.addColumn("Descrição");
        modelo.addColumn("Duração em minutos");
        modelo.addColumn("Gênero");

        tblAnimes.setModel(modelo);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca = new javax.swing.JTextField();
        pesquisar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimes = new javax.swing.JTable();
        btnCurtir = new javax.swing.JButton();
        btnDescurtir = new javax.swing.JButton();
        FEIFLIX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pesquisar.setText("Pesquisar:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        tblAnimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnimes);

        btnCurtir.setText("Curtir");
        btnCurtir.addActionListener(this::btnCurtirActionPerformed);

        btnDescurtir.setText("descurtir");
        btnDescurtir.addActionListener(this::btnDescurtirActionPerformed);

        FEIFLIX.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        FEIFLIX.setForeground(new java.awt.Color(204, 0, 0));
        FEIFLIX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FEIFLIX.setText("FEIFLIX");
        FEIFLIX.setToolTipText("");
        FEIFLIX.setPreferredSize(new java.awt.Dimension(100, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCurtir)
                        .addGap(33, 33, 33)
                        .addComponent(btnDescurtir)
                        .addGap(290, 290, 290)
                        .addComponent(FEIFLIX, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnCurtir)
                            .addComponent(btnDescurtir))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FEIFLIX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nomeBusca = txtBusca.getText();

        if (nomeBusca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome do anime.");
            return;
        }

        AnimesDAO dao = new AnimesDAO();
        ArrayList<Animes> lista = dao.buscarPorNome(nomeBusca);

        DefaultTableModel modelo = (DefaultTableModel) tblAnimes.getModel();
        modelo.setRowCount(0);

        for (Animes anime : lista) {
            modelo.addRow(new Object[]{
                anime.getIdAnimes(),
                anime.getTitulo(),
                anime.getDescricao(),
                anime.getDuracao(),
                anime.getGenero()
            });
        }

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum anime encontrado.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        JFrameMenu menu = new JFrameMenu(usuarioLogado);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        int linha = tblAnimes.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um anime na tabela.");
            return;
        }

        int idAnime = Integer.parseInt(tblAnimes.getValueAt(linha, 0).toString());

        AvaliacoesDAO dao = new AvaliacoesDAO();

        boolean sucesso = dao.avaliarAnime(
                usuarioLogado.getIdUsuario(),
                idAnime,
                "CURTIDO"
        );

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Anime curtido!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao curtir anime.");
        }
    }//GEN-LAST:event_btnCurtirActionPerformed

    private void btnDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescurtirActionPerformed
        int linha = tblAnimes.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um anime na tabela.");
            return;
        }

        int idAnime = Integer.parseInt(tblAnimes.getValueAt(linha, 0).toString());

        AvaliacoesDAO dao = new AvaliacoesDAO();

        boolean sucesso = dao.avaliarAnime(
                usuarioLogado.getIdUsuario(),
                idAnime,
                "DESCURTIDO"
        );

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Anime descurtido!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao descurtir anime.");
        }
    }//GEN-LAST:event_btnDescurtirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new JFrameBuscarAnime().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FEIFLIX;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnDescurtir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JTable tblAnimes;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

}